swagger: "2.0"
info:
  title: "Express API Gateway"
  description: "Main entry point for Frontend and Backend"
  version: "1.0.0"
schemes:
  - "https"
  - "http"
paths:
  # Route for Backend API
  /api/**:
    get:
      summary: "Forward to Backend Service"
      operationId: "backendRoute"
      x-google-backend:
        # Replace with your Backend LoadBalancer External IP
        address: http://34.x.x.x
      responses:
        200:
          description: "OK"

  # Route for Frontend Application
  /**:
    get:
      summary: "Forward to Frontend"
      operationId: "frontendRoute"
      x-google-backend:
        # Replace with your Frontend LoadBalancer External IP
        address: http://35.x.x.x
      responses:
        200:
          description: "OK"
